### ISSUE TITLE
Qt build errors on Mac OS

### ISSUE THREAD

**Issue by kotutuloro** [christopherpow/nesicide#22]
When I try to build on Mac OS 10.12 Sierra, I'm getting a series of errors.

The first error I get is "Qt requires C++11 support" (I'm using Qt 5.9.1). I get a series of other Qt related errors about undeclared identifiers before hitting "fatal error: too many errors emitted".

I'm not at all versed in Qt or C++, so I'm having trouble figuring out if this is an issue on my end or not.

**Comment by christopherpow** [comment]
Are you at HEAD on master?
Have you followed the README and downloaded/exploded the dependencies tarball?
I had this issue about a month ago and I'm not recalling what the solution was, at the moment. I seem to remember it having something to do with the version of Boost. I've updated to Boost 1.64.0 in the latest dependencies package.
Also, are you building using the build.sh script in build/? Or are you loading the subdirs project into Qt Creator and building in there?

**Comment by kotutuloro** [comment]
At HEAD on master
I exploded the tarball with the dependencies and the version of Boost I have is 1.64.0.
And I'm building in the build/ directory inside of nesicide.

I'm noticing that before the C++11 error, I'm also a ton of errors about unsigned ints.
For example:

common/cnessystempalette.cpp:58:4: error: constant expression evaluates to -1381126912 which cannot be narrowed to type 'uint32_t' (aka 'unsigned int') [-Wc++11-narrowing]
   RGB_VALUE ( 173, 173, 173 ),
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by christopherpow** [comment]
I am seeing this problem now. I recently upgraded from Qt 5.5 to Qt 5.9.1.
I am looking into the solution. Also, I started getting the int problems
too. I will push a fix for that. As for the c++11 thing, not sure on that
yet.

**Comment by kotutuloro** [comment]
(Sorry, I realized I haven't been getting notifications on this issue)
I've pulled all of the recent changes, and I'm no longer getting this same error.
But when I try to build now, 3 of the builds (ide, famitracker, and famiplayer) error out with:

In file included from cqtmfc_famitracker.cpp:1:
../../common/cqtmfc.h:2302:10: fatal error: 'windows.h' file not found
#include <windows.h>

NES emulator builds and deploys correctly as far as I can tell.

**Comment by christopherpow** [comment]
I noticed that. I have a fix. I'm not on my computer now but will push when
I can later tonight.

**Comment by christopherpow** [comment]
Please try now it should work.

**Comment by kotutuloro** [comment]
Not sure if the changes were pushed?

**Comment by christopherpow** [comment]
Ah. They were. But I need to upload a revised deps package. I should be
able to do that this evening. Will let you know.

**Comment by christopherpow** [comment]
I have uploaded a new nesicide-deps.tar.bz2. Please download it, explode
it, and try to build now. Thanks.

**Comment by christopherpow** [comment]
Actually, hang on. I need to do it once more.

**Comment by kotutuloro** [comment]
(Not sure if you were done with the deps but, the rtmidi dependency in the new tarball comes with a premade Makefile with the qmake path harcoded in, so it errored out. I went into /deps/rtmidi and removed the Makefile which solved it.) 

I came across this error when building IDE, FamiTracker, and FamiPlayer:

> Undefined symbols for architecture x86_64:
>   "RtMidiIn::RtMidiIn(RtMidi::Api, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int)", referenced from:
>       CMIDI::CMIDI() in MIDI.o
>   "MidiInApi::setCallback(void (*)(double, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*, void*), void*)", referenced from:
>       CMIDI::OpenDevices() in MIDI.o
>       CMIDI::ToggleInput() in MIDI.o
>   "MidiInApi::cancelCallback()", referenced from:
>       CMIDI::~CMIDI() in MIDI.o
>       CMIDI::CloseDevices() in MIDI.o
>       CMIDI::Shutdown() in MIDI.o
>       CMIDI::SetInputDevice(int, bool) in MIDI.o
>       CMIDI::SetOutputDevice(int) in MIDI.o
>       CMIDI::ToggleInput() in MIDI.o
>   "RtMidiOut::RtMidiOut(RtMidi::Api, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
>       CMIDI::CMIDI() in MIDI.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[1]: *** [release/libfamitracker.1.0.0.dylib] Error 1
> make: *** [sub-------libs-famitracker-famitracker-lib-pro-make_first] Error 2 

Adding a screenshot of everything it runs for FamiPlayer as an example in case that helps?
![screen shot 2017-10-10 at 2 58 43 pm](https://user-images.githubusercontent.com/18595173/31415257-1b7d1d90-add7-11e7-9c64-6bcad72eba01.png)


$ clang++ -v
> Apple LLVM version 8.1.0 (clang-802.0.42)
> Target: x86_64-apple-darwin16.4.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by christopherpow** [comment]
Grab everything fresh and try again. I am able to build in OSX.

**Comment by christopherpow** [comment]
Have you made any progress on this? I am able to build.

**Comment by TroyLong** [comment]
Yes. Thank you

**Comment by kotutuloro** [comment]
Started from scratch and everything builds beautifully!

Thank you so, so much for all of your work by the way! I really appreciate it.

**Comment by christopherpow** [comment]
Thanks! Enjoy!
