### ISSUE TITLE
Attempting Compilation on OSX

### ISSUE THREAD

**Issue by gootube2000** [christopherpow/nesicide#17]
I've never had much luck, nor truly went too far into compiling in general, but everytime I tried to compile it in Qt, I got the following message

In file included from cqtmfc_famitracker.cpp:1:
../../common/cqtmfc.h:2302:10: fatal error: 'windows.h' file not found
#include <windows.h>

Might anyone here know what I should do? And keep in mind I still have trouble understanding this entirely.

**Comment by christopherpow** [comment]
Hm. I thought I had uploaded a new deps.tar.bz2 with the WINE headers in
it. Now that I'm looking there it doesn't have it.

I'll get that put in today. That should solve your windows.h problem.

**Comment by christopherpow** [comment]
I've uploaded a new deps package. Download it and explode it into nesicide/...

It has the WINE headers for osx, among other things.

**Comment by brovador** [comment]
I'm having problems too trying to compile in OSX 10.10. I've installed qmake using homebrew and after running ```make``` I'm getting this error:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C libs/famitracker
g++ -c -pipe -I../../deps/osx/SDL.framework/Headers -I../../deps/osx/../boost_1_58_0 -I ../../deps/osx/wine/include -DWINE_UNICODE_NATIVE -I ../../deps/osx -I ../../deps/osx/stdafxhack -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W -Wno-reorder -Wno-unused -isysroot macosx10.10 -fPIC -DNOMINMAX -DNULL=0 -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/local/Cellar/qt/4.8.6/mkspecs/macx-g++ -I. -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/include -I. -ISource -I../../common -Irelease -F/usr/local/Cellar/qt/4.8.6/lib -o release/cqtmfc_famitracker.o cqtmfc_famitracker.cpp
clang: warning: no such sysroot directory: 'macosx10.10'
In file included from cqtmfc_famitracker.cpp:1:
In file included from ../../common/cqtmfc.h:7:
In file included from /usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers/QDialogButtonBox:1:
In file included from /usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers/qdialogbuttonbox.h:45:
In file included from /usr/local/Cellar/qt/4.8.6/include/QtGui/qwidget.h:46:
In file included from /usr/local/Cellar/qt/4.8.6/include/QtGui/qwindowdefs.h:45:
In file included from /usr/local/Cellar/qt/4.8.6/include/QtCore/qobjectdefs.h:45:
In file included from /usr/local/Cellar/qt/4.8.6/include/QtCore/qnamespace.h:45:
/usr/local/Cellar/qt/4.8.6/include/QtCore/qglobal.h:68:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^
1 error generated.
make[1]: *** [release/cqtmfc_famitracker.o] Error 1
make: *** [libs/famitracker/libfamitracker.so.1.0.0] Error 2
```

Any ideas?

**Comment by christopherpow** [comment]
I added Boost to dependencies since it is required by FamiTracker 0.4.6 - that might be it. I'll upload a new deps package tonight.

**Comment by christopherpow** [comment]
You need to download boost_1_58_0.tar.bz2. Extract that into nesicide/deps.
The algorithm header file is in there. I'd add it as part of the
deps.tar.bz2 package but there's not enough room to upload that onto my
google site.

**Comment by thisisablock** [comment]
@brovador got the same error - i fixed it by replacing the all macosx10.10 variables inside the make files with "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk"

but i get another error

In file included from ../../common/cqtmfc.cpp:1:
In file included from /usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers/QCoreApplication:1:
In file included from /usr/local/Cellar/qt/4.8.6/include/QtCore/qcoreapplication.h:45:
In file included from /usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers/qobject.h:50:
/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers/qlist.h:381:22: warning: source of this 'memcpy' call is a pointer to dynamic class 'CString';
      vtable pointer will be copied [-Wdynamic-class-memaccess]
    else ::memcpy(n, &t, sizeof(T));
         ~~~~~~~~    ^
/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers/qlist.h:512:13: note: in instantiation of member function 'QList<CString>::node_construct' requested
      here
            node_construct(n, t);
            ^
../../common/cqtmfc.cpp:2078:11: note: in instantiation of member function 'QList<CString>::append' requested here
   _qlist.append(CString(newElement));
          ^
/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers/qlist.h:381:22: note: explicitly cast the pointer to silence this warning
    else ::memcpy(n, &t, sizeof(T));
                     ^
                     (void*)
311 warnings and 1 error generated.
make[1]: *** [release/cqtmfc.o] Error 1
make: *** [libs/famitracker/libfamitracker.so.1.0.0] Error 2

**Comment by AugustNagro** [comment]
Any update on this?

**Comment by christopherpow** [comment]
I have managed to build in OSX but the deployment refuses to include CC65. Trying to get that sorted then I'll post a DMG.

**Comment by AugustNagro** [comment]
Thanks a lot!

**Comment by christopherpow** [comment]
Download this DMG:
https://drive.google.com/file/d/0BwhBNo66Kd6bWXc3bGJjTjZaXzA/view?usp=sharing
And download this dependencies package:
https://drive.google.com/file/d/0BwhBNo66Kd6baGlkRHZvV2lFRU0/view?usp=sharing

Install the DMG into your /Applications, then copy the cc65 folder entirely into /Applications/nesicide.app/Contents/MacOS/

If you've done it right the Environment Settings dialog should show you that it found the CC65 toolchain on the Compiler tab.

There's a crash on close that I'm looking into but otherwise it should work to compile/run.

**Comment by jordo** [comment]
Trying to build too...   MAC_SDK needs to get updated to 10.11 for Yosemite.

**Comment by christopherpow** [comment]
Somehow those didn't get committed. I'll push tonight. Thanks for the catch.

**Comment by christopherpow** [comment]
MAC_SDK updated.

**Comment by jordo** [comment]
Awesome thanks so much!   Can you post a new deps package for OSX somewhere?  I'm trying to find rtmidi again as it was removed from libs to deps a few commits ago.

**Comment by christopherpow** [comment]
Done.https://drive.google.com/file/d/0BwhBNo66Kd6bUXhsOUtrM1lndUU/view?usp=sharing
